version: "3.7"

services:
  my_receive_broker:
    container_name: broker_receiver
    image: my_receive_broker
    volumes:
      - /tmp/python_unix_sockets_example:/tmp/python_unix_sockets_example
    # ports:
    #   - 127.0.0.1:5672:5672
    #   - 127.0.0.1:15672:15672
    depends_on:
      - my_sender_azure
      - rabbitmq_local

  my_sender_azure:
    container_name: sender_azure
    image: my_sender_azure
    environment:
      - IOTHUB_DEVICE_SECURITY_TYPE=${IOTHUB_DEVICE_SECURITY_TYPE}
      - IOTHUB_DEVICE_CONNECTION_STRING=${IOTHUB_DEVICE_CONNECTION_STRING}
    volumes:
      - /tmp/python_unix_sockets_example:/tmp/python_unix_sockets_example
  
  rabbitmq_local:
    image: rabbitmq:3
    container_name: rabbitmq_local
    ports:
      - 5672:5672
      - 15672:15672