version: "3.7"

services:
  my_receive_broker:
    container_name: broker_receiver
    image: my_receive_broker
    environment:
      # - AMQP_HOST='host.docker.internal'
      - AMQP_HOST='host.docker.internal:host-gateway'
    volumes:
      - /tmp/python_unix_sockets_example:/tmp/python_unix_sockets_example
    # ports:
    #   - 5672:5672
    #   - 127.0.0.1:15672:15672
    # depends_on:
    #   # - my_sender_azure
    #   rabbitmq_local:
    #     condition: service_started

  my_broker_emitter:
    container_name: broker_emitter
    image: my_broker_emitter
    environment:
      # - AMQP_HOST='host.docker.internal'
      - AMQP_HOST='host.docker.internal:host-gateway'
    # ports:
    # - 5672:5672
    # depends_on:
    #   rabbitmq_local:
    #     condition: service_started


  # my_sender_azure:
  #   container_name: sender_azure
  #   image: my_sender_azure
  #   environment:
  #     - IOTHUB_DEVICE_SECURITY_TYPE=${IOTHUB_DEVICE_SECURITY_TYPE}
  #     - IOTHUB_DEVICE_CONNECTION_STRING=${IOTHUB_DEVICE_CONNECTION_STRING}
  #   volumes:
  #     - /tmp/python_unix_sockets_example:/tmp/python_unix_sockets_example
  
  # rabbitmq_local:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq_local
  #   ports:
  #     - 5672:5672
  #     - 15672:15672