FROM ubuntu:20.04

RUN apt update
RUN apt install -y python3 python3-pip python3-dev build-essential gcc

RUN pip3 install --upgrade pip

RUN mkdir /app
WORKDIR /app
COPY ./socket_server.py /app

CMD ["python3", "socket_server.py"]
